#include <iostream>

#include "BigInt.hpp"

int main()
{
	try
	{
		BigInt i = 5134;
		BigInt j = 584663;

		std::cout << (i + j) << std::endl;
		std::cout << (i - j) << std::endl;
		std::cout << (i * j) << std::endl;
		std::cout << (i + j) << std::endl;
	}
	catch (const std::exception& ex)
	{
		std::cerr << ex.what() << std::endl;
	}

	return 0;
}
